<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ciudades')->insert([
            ['ciudad' => 'CUENCA', 'codigo' => '0101', 'provincia_id' => 1],
            ['ciudad' => 'GIRÓN', 'codigo' => '0102', 'provincia_id' => 1],
            ['ciudad' => 'GUALACEO', 'codigo' => '0103', 'provincia_id' => 1],
            ['ciudad' => 'NABÓN', 'codigo' => '0104', 'provincia_id' => 1],
            ['ciudad' => 'PAUTE', 'codigo' => '0105', 'provincia_id' => 1],
            ['ciudad' => 'PUCARA', 'codigo' => '0106', 'provincia_id' => 1],
            ['ciudad' => 'SAN FERNANDO', 'codigo' => '0107', 'provincia_id' => 1],
            ['ciudad' => 'SANTA ISABEL', 'codigo' => '0108', 'provincia_id' => 1],
            ['ciudad' => 'SIGSIG', 'codigo' => '0109', 'provincia_id' => 1],
            ['ciudad' => 'OÑA', 'codigo' => '0110', 'provincia_id' => 1],
            ['ciudad' => 'CHORDELEG', 'codigo' => '0111', 'provincia_id' => 1],
            ['ciudad' => 'EL PAN', 'codigo' => '0112', 'provincia_id' => 1],
            ['ciudad' => 'SEVILLA DE ORO', 'codigo' => '0113', 'provincia_id' => 1],
            ['ciudad' => 'GUACHAPALA', 'codigo' => '0114', 'provincia_id' => 1],
            ['ciudad' => 'CAMILO PONCE ENRÍQUEZ', 'codigo' => '0115', 'provincia_id' => 1],
            ['ciudad' => 'GUARANDA', 'codigo' => '0201', 'provincia_id' => 2],
            ['ciudad' => 'CHILLANES', 'codigo' => '0202', 'provincia_id' => 2],
            ['ciudad' => 'CHIMBO', 'codigo' => '0203', 'provincia_id' => 2],
            ['ciudad' => 'ECHEANDÍA', 'codigo' => '0204', 'provincia_id' => 2],
            ['ciudad' => 'SAN MIGUEL', 'codigo' => '0205', 'provincia_id' => 2],
            ['ciudad' => 'CALUMA', 'codigo' => '0206', 'provincia_id' => 2],
            ['ciudad' => 'LAS NAVES', 'codigo' => '0207', 'provincia_id' => 2],
            ['ciudad' => 'AZOGUES', 'codigo' => '0301', 'provincia_id' => 3],
            ['ciudad' => 'BIBLIÁN', 'codigo' => '0302', 'provincia_id' => 3],
            ['ciudad' => 'CAÑAR', 'codigo' => '0303', 'provincia_id' => 3],
            ['ciudad' => 'LA TRONCAL', 'codigo' => '0304', 'provincia_id' => 3],
            ['ciudad' => 'EL TAMBO', 'codigo' => '0305', 'provincia_id' => 3],
            ['ciudad' => 'DÉLEG', 'codigo' => '0306', 'provincia_id' => 3],
            ['ciudad' => 'SUSCAL', 'codigo' => '0307', 'provincia_id' => 3],
            ['ciudad' => 'TULCÁN', 'codigo' => '0401', 'provincia_id' => 4],
            ['ciudad' => 'BOLÍVAR', 'codigo' => '0402', 'provincia_id' => 4],
            ['ciudad' => 'ESPEJO', 'codigo' => '0403', 'provincia_id' => 4],
            ['ciudad' => 'MIRA', 'codigo' => '0404', 'provincia_id' => 4],
            ['ciudad' => 'MONTÚFAR', 'codigo' => '0405', 'provincia_id' => 4],
            ['ciudad' => 'SAN PEDRO DE HUACA', 'codigo' => '0406', 'provincia_id' => 4],
            ['ciudad' => 'LATACUNGA', 'codigo' => '0501', 'provincia_id' => 5],
            ['ciudad' => 'LA MANÁ', 'codigo' => '0502', 'provincia_id' => 5],
            ['ciudad' => 'PANGUA', 'codigo' => '0503', 'provincia_id' => 5],
            ['ciudad' => 'PUJILI', 'codigo' => '0504', 'provincia_id' => 5],
            ['ciudad' => 'SALCEDO', 'codigo' => '0505', 'provincia_id' => 5],
            ['ciudad' => 'SAQUISILÍ', 'codigo' => '0506', 'provincia_id' => 5],
            ['ciudad' => 'SIGCHOS', 'codigo' => '0507', 'provincia_id' => 5],
            ['ciudad' => 'RIOBAMBA', 'codigo' => '0601', 'provincia_id' => 6],
            ['ciudad' => 'ALAUSI', 'codigo' => '0602', 'provincia_id' => 6],
            ['ciudad' => 'COLTA', 'codigo' => '0603', 'provincia_id' => 6],
            ['ciudad' => 'CHAMBO', 'codigo' => '0604', 'provincia_id' => 6],
            ['ciudad' => 'CHUNCHI', 'codigo' => '0605', 'provincia_id' => 6],
            ['ciudad' => 'GUAMOTE', 'codigo' => '0606', 'provincia_id' => 6],
            ['ciudad' => 'GUANO', 'codigo' => '0607', 'provincia_id' => 6],
            ['ciudad' => 'PALLATANGA', 'codigo' => '0608', 'provincia_id' => 6],
            ['ciudad' => 'PENIPE', 'codigo' => '0609', 'provincia_id' => 6],
            ['ciudad' => 'CUMANDÁ', 'codigo' => '0610', 'provincia_id' => 6],
            ['ciudad' => 'MACHALA', 'codigo' => '0701', 'provincia_id' => 7],
            ['ciudad' => 'ARENILLAS', 'codigo' => '0702', 'provincia_id' => 7],
            ['ciudad' => 'ATAHUALPA', 'codigo' => '0703', 'provincia_id' => 7],
            ['ciudad' => 'BALSAS', 'codigo' => '0704', 'provincia_id' => 7],
            ['ciudad' => 'CHILLA', 'codigo' => '0705', 'provincia_id' => 7],
            ['ciudad' => 'EL GUABO', 'codigo' => '0706', 'provincia_id' => 7],
            ['ciudad' => 'HUAQUILLAS', 'codigo' => '0707', 'provincia_id' => 7],
            ['ciudad' => 'MARCABELÍ', 'codigo' => '0708', 'provincia_id' => 7],
            ['ciudad' => 'PASAJE', 'codigo' => '0709', 'provincia_id' => 7],
            ['ciudad' => 'PIÑAS', 'codigo' => '0710', 'provincia_id' => 7],
            ['ciudad' => 'PORTOVELO', 'codigo' => '0711', 'provincia_id' => 7],
            ['ciudad' => 'SANTA ROSA', 'codigo' => '0712', 'provincia_id' => 7],
            ['ciudad' => 'ZARUMA', 'codigo' => '0713', 'provincia_id' => 7],
            ['ciudad' => 'LAS LAJAS', 'codigo' => '0714', 'provincia_id' => 7],
            ['ciudad' => 'ESMERALDAS', 'codigo' => '0801', 'provincia_id' => 8],
            ['ciudad' => 'MUISNE', 'codigo' => '0803', 'provincia_id' => 8],
            ['ciudad' => 'QUININDÉ', 'codigo' => '0804', 'provincia_id' => 8],
            ['ciudad' => 'SAN LORENZO', 'codigo' => '0805', 'provincia_id' => 8],
            ['ciudad' => 'ATACAMES', 'codigo' => '0806', 'provincia_id' => 8],
            ['ciudad' => 'RIOVERDE', 'codigo' => '0807', 'provincia_id' => 8],
            ['ciudad' => 'LA CONCORDIA', 'codigo' => '0808', 'provincia_id' => 8],
            ['ciudad' => 'GUAYAQUIL', 'codigo' => '0901', 'provincia_id' => 9],
            ['ciudad' => 'ALFREDO BAQUERIZO MORENO (JUJÁN)', 'codigo' => '0902', 'provincia_id' => 9],
            ['ciudad' => 'BALAO', 'codigo' => '0903', 'provincia_id' => 9],
            ['ciudad' => 'BALZAR', 'codigo' => '0904', 'provincia_id' => 9],
            ['ciudad' => 'COLIMES', 'codigo' => '0905', 'provincia_id' => 9],
            ['ciudad' => 'DAULE', 'codigo' => '0906', 'provincia_id' => 9],
            ['ciudad' => 'DURÁN', 'codigo' => '0907', 'provincia_id' => 9],
            ['ciudad' => 'EL EMPALME', 'codigo' => '0908', 'provincia_id' => 9],
            ['ciudad' => 'EL TRIUNFO', 'codigo' => '0909', 'provincia_id' => 9],
            ['ciudad' => 'MILAGRO', 'codigo' => '0910', 'provincia_id' => 9],
            ['ciudad' => 'NARANJAL', 'codigo' => '0911', 'provincia_id' => 9],
            ['ciudad' => 'NARANJITO', 'codigo' => '0912', 'provincia_id' => 9],
            ['ciudad' => 'PALESTINA', 'codigo' => '0913', 'provincia_id' => 9],
            ['ciudad' => 'PEDRO CARBO', 'codigo' => '0914', 'provincia_id' => 9],
            ['ciudad' => 'SAMBORONDÓN', 'codigo' => '0916', 'provincia_id' => 9],
            ['ciudad' => 'SANTA LUCÍA', 'codigo' => '0918', 'provincia_id' => 9],
            ['ciudad' => 'SALITRE (URBINA JADO)', 'codigo' => '0919', 'provincia_id' => 9],
            ['ciudad' => 'SAN JACINTO DE YAGUACHI', 'codigo' => '0920', 'provincia_id' => 9],
            ['ciudad' => 'PLAYAS', 'codigo' => '0921', 'provincia_id' => 9],
            ['ciudad' => 'SIMÓN BOLÍVAR', 'codigo' => '0922', 'provincia_id' => 9],
            ['ciudad' => 'CORONEL MARCELINO MARIDUEÑA', 'codigo' => '0923', 'provincia_id' => 9],
            ['ciudad' => 'LOMAS DE SARGENTILLO', 'codigo' => '0924', 'provincia_id' => 9],
            ['ciudad' => 'NOBOL', 'codigo' => '0925', 'provincia_id' => 9],
            ['ciudad' => 'GENERAL ANTONIO ELIZALDE', 'codigo' => '0927', 'provincia_id' => 9],
            ['ciudad' => 'ISIDRO AYORA', 'codigo' => '0928', 'provincia_id' => 9],
            ['ciudad' => 'IBARRA', 'codigo' => '1001', 'provincia_id' => 10],
            ['ciudad' => 'ANTONIO ANTE', 'codigo' => '1002', 'provincia_id' => 10],
            ['ciudad' => 'COTACACHI', 'codigo' => '1003', 'provincia_id' => 10],
            ['ciudad' => 'OTAVALO', 'codigo' => '1004', 'provincia_id' => 10],
            ['ciudad' => 'PIMAMPIRO', 'codigo' => '1005', 'provincia_id' => 10],
            ['ciudad' => 'SAN MIGUEL DE URCUQUÍ', 'codigo' => '1006', 'provincia_id' => 10],
            ['ciudad' => 'LOJA', 'codigo' => '1101', 'provincia_id' => 11],
            ['ciudad' => 'CALVAS', 'codigo' => '1102', 'provincia_id' => 11],
            ['ciudad' => 'CATAMAYO', 'codigo' => '1103', 'provincia_id' => 11],
            ['ciudad' => 'CELICA', 'codigo' => '1104', 'provincia_id' => 11],
            ['ciudad' => 'CHAGUARPAMBA', 'codigo' => '1105', 'provincia_id' => 11],
            ['ciudad' => 'ESPÍNDOLA', 'codigo' => '1106', 'provincia_id' => 11],
            ['ciudad' => 'GONZANAMÁ', 'codigo' => '1107', 'provincia_id' => 11],
            ['ciudad' => 'MACARÁ', 'codigo' => '1108', 'provincia_id' => 11],
            ['ciudad' => 'PALTAS', 'codigo' => '1109', 'provincia_id' => 11],
            ['ciudad' => 'PUYANGO', 'codigo' => '1110', 'provincia_id' => 11],
            ['ciudad' => 'SARAGURO', 'codigo' => '1111', 'provincia_id' => 11],
            ['ciudad' => 'SOZORANGA', 'codigo' => '1112', 'provincia_id' => 11],
            ['ciudad' => 'ZAPOTILLO', 'codigo' => '1113', 'provincia_id' => 11],
            ['ciudad' => 'PINDAL', 'codigo' => '1114', 'provincia_id' => 11],
            ['ciudad' => 'QUILANGA', 'codigo' => '1115', 'provincia_id' => 11],
            ['ciudad' => 'OLMEDO', 'codigo' => '1116', 'provincia_id' => 11],
            ['ciudad' => 'BABAHOYO', 'codigo' => '1201', 'provincia_id' => 12],
            ['ciudad' => 'BABA', 'codigo' => '1202', 'provincia_id' => 12],
            ['ciudad' => 'MONTALVO', 'codigo' => '1203', 'provincia_id' => 12],
            ['ciudad' => 'PUEBLOVIEJO', 'codigo' => '1204', 'provincia_id' => 12],
            ['ciudad' => 'QUEVEDO', 'codigo' => '1205', 'provincia_id' => 12],
            ['ciudad' => 'URDANETA', 'codigo' => '1206', 'provincia_id' => 12],
            ['ciudad' => 'VENTANAS', 'codigo' => '1207', 'provincia_id' => 12],
            ['ciudad' => 'VÍNCES', 'codigo' => '1208', 'provincia_id' => 12],
            ['ciudad' => 'PALENQUE', 'codigo' => '1209', 'provincia_id' => 12],
            ['ciudad' => 'BUENA FÉ', 'codigo' => '1210', 'provincia_id' => 12],
            ['ciudad' => 'VALENCIA', 'codigo' => '1211', 'provincia_id' => 12],
            ['ciudad' => 'MOCACHE', 'codigo' => '1212', 'provincia_id' => 12],
            ['ciudad' => 'QUINSALOMA', 'codigo' => '1213', 'provincia_id' => 12],
            ['ciudad' => 'PORTOVIEJO', 'codigo' => '1301', 'provincia_id' => 13],
            ['ciudad' => 'BOLÍVAR', 'codigo' => '1302', 'provincia_id' => 13],
            ['ciudad' => 'CHONE', 'codigo' => '1303', 'provincia_id' => 13],
            ['ciudad' => 'EL CARMEN', 'codigo' => '1304', 'provincia_id' => 13],
            ['ciudad' => 'FLAVIO ALFARO', 'codigo' => '1305', 'provincia_id' => 13],
            ['ciudad' => 'JIPIJAPA', 'codigo' => '1306', 'provincia_id' => 13],
            ['ciudad' => 'JUNÍN', 'codigo' => '1307', 'provincia_id' => 13],
            ['ciudad' => 'MANTA', 'codigo' => '1308', 'provincia_id' => 13],
            ['ciudad' => 'MONTECRISTI', 'codigo' => '1309', 'provincia_id' => 13],
            ['ciudad' => 'PAJÁN', 'codigo' => '1310', 'provincia_id' => 13],
            ['ciudad' => 'PICHINCHA', 'codigo' => '1311', 'provincia_id' => 13],
            ['ciudad' => 'ROCAFUERTE', 'codigo' => '1312', 'provincia_id' => 13],
            ['ciudad' => 'SANTA ANA', 'codigo' => '1313', 'provincia_id' => 13],
            ['ciudad' => 'SUCRE', 'codigo' => '1314', 'provincia_id' => 13],
            ['ciudad' => 'TOSAGUA', 'codigo' => '1315', 'provincia_id' => 13],
            ['ciudad' => '24 DE MAYO', 'codigo' => '1316', 'provincia_id' => 13],
            ['ciudad' => 'PEDERNALES', 'codigo' => '1317', 'provincia_id' => 13],
            ['ciudad' => 'OLMEDO', 'codigo' => '1318', 'provincia_id' => 13],
            ['ciudad' => 'PUERTO LÓPEZ', 'codigo' => '1319', 'provincia_id' => 13],
            ['ciudad' => 'JAMA', 'codigo' => '1320', 'provincia_id' => 13],
            ['ciudad' => 'JARAMIJÓ', 'codigo' => '1321', 'provincia_id' => 13],
            ['ciudad' => 'SAN VICENTE', 'codigo' => '1322', 'provincia_id' => 13],
            ['ciudad' => 'MORONA', 'codigo' => '1401', 'provincia_id' => 14],
            ['ciudad' => 'GUALAQUIZA', 'codigo' => '1402', 'provincia_id' => 14],
            ['ciudad' => 'LIMÓN INDANZA', 'codigo' => '1403', 'provincia_id' => 14],
            ['ciudad' => 'PALORA', 'codigo' => '1404', 'provincia_id' => 14],
            ['ciudad' => 'SANTIAGO', 'codigo' => '1405', 'provincia_id' => 14],
            ['ciudad' => 'SUCÚA', 'codigo' => '1406', 'provincia_id' => 14],
            ['ciudad' => 'HUAMBOYA', 'codigo' => '1407', 'provincia_id' => 14],
            ['ciudad' => 'SAN JUAN BOSCO', 'codigo' => '1408', 'provincia_id' => 14],
            ['ciudad' => 'TAISHA', 'codigo' => '1409', 'provincia_id' => 14],
            ['ciudad' => 'LOGROÑO', 'codigo' => '1410', 'provincia_id' => 14],
            ['ciudad' => 'PABLO SEXTO', 'codigo' => '1411', 'provincia_id' => 14],
            ['ciudad' => 'TIWINTZA', 'codigo' => '1412', 'provincia_id' => 14],
            ['ciudad' => 'TENA', 'codigo' => '1501', 'provincia_id' => 15],
            ['ciudad' => 'ARCHIDONA', 'codigo' => '1503', 'provincia_id' => 15],
            ['ciudad' => 'EL CHACO', 'codigo' => '1504', 'provincia_id' => 15],
            ['ciudad' => 'QUIJOS', 'codigo' => '1507', 'provincia_id' => 15],
            ['ciudad' => 'CARLOS JULIO AROSEMENA TOLA', 'codigo' => '1509', 'provincia_id' => 15],
            ['ciudad' => 'PASTAZA', 'codigo' => '1601', 'provincia_id' => 16],
            ['ciudad' => 'MERA', 'codigo' => '1602', 'provincia_id' => 16],
            ['ciudad' => 'SANTA CLARA', 'codigo' => '1603', 'provincia_id' => 16],
            ['ciudad' => 'ARAJUNO', 'codigo' => '1604', 'provincia_id' => 16],
            ['ciudad' => 'QUITO', 'codigo' => '1701', 'provincia_id' => 17],
            ['ciudad' => 'CAYAMBE', 'codigo' => '1702', 'provincia_id' => 17],
            ['ciudad' => 'MEJIA', 'codigo' => '1703', 'provincia_id' => 17],
            ['ciudad' => 'PEDRO MONCAYO', 'codigo' => '1704', 'provincia_id' => 17],
            ['ciudad' => 'RUMIÑAHUI', 'codigo' => '1705', 'provincia_id' => 17],
            ['ciudad' => 'SAN MIGUEL DE LOS BANCOS', 'codigo' => '1707', 'provincia_id' => 17],
            ['ciudad' => 'PEDRO VICENTE MALDONADO', 'codigo' => '1708', 'provincia_id' => 17],
            ['ciudad' => 'PUERTO QUITO', 'codigo' => '1709', 'provincia_id' => 17],
            ['ciudad' => 'AMBATO', 'codigo' => '1801', 'provincia_id' => 18],
            ['ciudad' => 'BAÑOS DE AGUA SANTA', 'codigo' => '1802', 'provincia_id' => 18],
            ['ciudad' => 'CEVALLOS', 'codigo' => '1803', 'provincia_id' => 18],
            ['ciudad' => 'MOCHA', 'codigo' => '1804', 'provincia_id' => 18],
            ['ciudad' => 'PATATE', 'codigo' => '1805', 'provincia_id' => 18],
            ['ciudad' => 'QUERO', 'codigo' => '1806', 'provincia_id' => 18],
            ['ciudad' => 'SAN PEDRO DE PELILEO', 'codigo' => '1807', 'provincia_id' => 18],
            ['ciudad' => 'SANTIAGO DE PÍLLARO', 'codigo' => '1808', 'provincia_id' => 18],
            ['ciudad' => 'TISALEO', 'codigo' => '1809', 'provincia_id' => 18],
            ['ciudad' => 'ZAMORA', 'codigo' => '1901', 'provincia_id' => 19],
            ['ciudad' => 'CHINCHIPE', 'codigo' => '1902', 'provincia_id' => 19],
            ['ciudad' => 'NANGARITZA', 'codigo' => '1903', 'provincia_id' => 19],
            ['ciudad' => 'YACUAMBI', 'codigo' => '1904', 'provincia_id' => 19],
            ['ciudad' => 'YANTZAZA (YANZATZA)', 'codigo' => '1905', 'provincia_id' => 19],
            ['ciudad' => 'EL PANGUI', 'codigo' => '1906', 'provincia_id' => 19],
            ['ciudad' => 'CENTINELA DEL CÓNDOR', 'codigo' => '1907', 'provincia_id' => 19],
            ['ciudad' => 'PALANDA', 'codigo' => '1908', 'provincia_id' => 19],
            ['ciudad' => 'PAQUISHA', 'codigo' => '1909', 'provincia_id' => 19],
            ['ciudad' => 'SAN CRISTÓBAL', 'codigo' => '2001', 'provincia_id' => 20],
            ['ciudad' => 'ISABELA', 'codigo' => '2002', 'provincia_id' => 20],
            ['ciudad' => 'SANTA CRUZ', 'codigo' => '2003', 'provincia_id' => 20],
            ['ciudad' => 'LAGO AGRIO', 'codigo' => '2101', 'provincia_id' => 21],
            ['ciudad' => 'GONZALO PIZARRO', 'codigo' => '2102', 'provincia_id' => 21],
            ['ciudad' => 'PUTUMAYO', 'codigo' => '2103', 'provincia_id' => 21],
            ['ciudad' => 'SHUSHUFINDI', 'codigo' => '2104', 'provincia_id' => 21],
            ['ciudad' => 'SUCUMBÍOS', 'codigo' => '2105', 'provincia_id' => 21],
            ['ciudad' => 'CASCALES', 'codigo' => '2106', 'provincia_id' => 21],
            ['ciudad' => 'CUYABENO', 'codigo' => '2107', 'provincia_id' => 21],
            ['ciudad' => 'ORELLANA', 'codigo' => '2201', 'provincia_id' => 22],
            ['ciudad' => 'AGUARICO', 'codigo' => '2202', 'provincia_id' => 22],
            ['ciudad' => 'LA JOYA DE LOS SACHAS', 'codigo' => '2203', 'provincia_id' => 22],
            ['ciudad' => 'LORETO', 'codigo' => '2204', 'provincia_id' => 22],
            ['ciudad' => 'SANTO DOMINGO', 'codigo' => '2301', 'provincia_id' => 23],
            ['ciudad' => 'SANTA ELENA', 'codigo' => '2401', 'provincia_id' => 24],
            ['ciudad' => 'LA LIBERTAD', 'codigo' => '2402', 'provincia_id' => 24],
            ['ciudad' => 'SALINAS', 'codigo' => '2403', 'provincia_id' => 24],
            ['ciudad' => 'LAS GOLONDRINAS', 'codigo' => '9001', 'provincia_id' => 90],
            ['ciudad' => 'MANGA DEL CURA', 'codigo' => '9003', 'provincia_id' => 90],
            ['ciudad' => 'EL PIEDRERO', 'codigo' => '9004', 'provincia_id' => 90],
        ]);
    }
}
