services:
  mysql:
    container_name: electronica
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=electronica"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
    ports:
      - "3306:3306"
